### ISSUE TITLE
SHK-101-AP-aIOS-8821.txt .. please create new template 

### ISSUE THREAD

**Issue by AirManic** [nickrusso42518/mhk#17]
To help streamline testing/validation.. please add a config template based on the following.  The hostname & filename are not sacred.  Main streamlining here is to sync up the WPA-PSK.

no service pad
service timestamps debug datetime msec
service timestamps log datetime msec
service password-encryption
!
hostname {{SSHK-101-AP-aIOS-8821}}
!
!
logging rate-limit console 9
enable secret {{SHK-101-PASSWORD}}
!
no aaa new-model
no ip source-route
no ip cef
no ip dhcp conflict logging
ip dhcp excluded-address 10.0.0.254 10.0.0.255
!
ip dhcp pool POOL_Cisco8821-Provision
 network 10.0.0.0 255.255.255.0
 option 150 ip 10.0.0.254 
 lease 0 0 10
!
dot11 pause-time 100
dot11 syslog
!
dot11 ssid {{SHK-101-DATA}}
   authentication open 
   authentication key-management wpa version 2
   wpa-psk ascii {{SHK-101-DATA-PSK}}
!
dot11 ssid {{SHK-101-BIOMED}}
   authentication open 
   authentication key-management wpa version 2
   wpa-psk ascii {{SHK-101-BIOMED-PSK}}
!
dot11 ssid {{SHK-101-VOICE}}
   authentication open 
   authentication key-management wpa version 2
   wpa-psk ascii {{SHK-101-VOICE-PSK}}
!
dot11 ssid cisco
   authentication open 
!
!
!
no ipv6 cef
!
!
username {{SHK-101-ADMIN}} password {{SHK-101-PASSWORD}}
!
!
bridge irb
!
!
!
interface Dot11Radio0
 no ip address
 no shutdown
 !
 ssid cisco
 !
 antenna gain 0
 stbc
 station-role root access-point
 bridge-group 1
 bridge-group 1 subscriber-loop-control
 bridge-group 1 spanning-disabled
 bridge-group 1 block-unknown-source
 no bridge-group 1 source-learning
 no bridge-group 1 unicast-flooding
!
interface Dot11Radio1
 no ip address
 shutdown
 !
 encryption mode ciphers aes-ccm 
 !
 ssid SHK-101-DATA
 !
 antenna gain 0
 peakdetect
 stbc
 station-role workgroup-bridge
 bridge-group 1
 bridge-group 1 spanning-disabled
!
interface GigabitEthernet0
 no ip address
 duplex auto
 speed auto
 bridge-group 1
 bridge-group 1 spanning-disabled
!
interface BVI1
 ip address 10.0.0.254 255.255.255.0
 ipv6 address dhcp
 ipv6 address autoconfig
 ipv6 enable
!
ip forward-protocol nd
no ip http server
no ip http secure-server
!
tftp-server flash:8821-WLANDefault.xml
!
bridge 1 route ip
!
line con 0
 exec-timeout 480 0
 logging synchronous
 login local
line vty 0 4
 exec-timeout 480 0
 logging synchronous
 login local
 transport input all
!
end

**Comment by AirManic** [comment]
Should have mentioned.. with a few CLI change to BVI and shutdown of do0 and enable do1 with a specific SSID, this config also serves as quick test client of each SSID.  That is the real reason for PSK alignment.

**Comment by nickrusso42518** [comment]
For simplicity and consistency, I've named the file `wgb.txt` instead.

**Comment by AirManic** [comment]
PERFECT.  Counted on your discretion.  I am focused on functionality, not naming.  .:|:.:|:. Gordon Rogier
